
package com.objis.demo.soap.typescomplexes.teamsClient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Teams", targetNamespace = "http://teamsService.typescomplexes.demo.soap.objis.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Teams {


    /**
     * 
     * @return
     *     returns java.util.List<com.objis.demo.soap.typescomplexes.teamsClient.Team>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTeams", targetNamespace = "http://teamsService.typescomplexes.demo.soap.objis.com/", className = "com.objis.demo.soap.typescomplexes.teamsClient.GetTeams")
    @ResponseWrapper(localName = "getTeamsResponse", targetNamespace = "http://teamsService.typescomplexes.demo.soap.objis.com/", className = "com.objis.demo.soap.typescomplexes.teamsClient.GetTeamsResponse")
    @Action(input = "http://teamsService.typescomplexes.demo.soap.objis.com/Teams/getTeamsRequest", output = "http://teamsService.typescomplexes.demo.soap.objis.com/Teams/getTeamsResponse")
    public List<Team> getTeams();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.objis.demo.soap.typescomplexes.teamsClient.Team
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTeam", targetNamespace = "http://teamsService.typescomplexes.demo.soap.objis.com/", className = "com.objis.demo.soap.typescomplexes.teamsClient.GetTeam")
    @ResponseWrapper(localName = "getTeamResponse", targetNamespace = "http://teamsService.typescomplexes.demo.soap.objis.com/", className = "com.objis.demo.soap.typescomplexes.teamsClient.GetTeamResponse")
    @Action(input = "http://teamsService.typescomplexes.demo.soap.objis.com/Teams/getTeamRequest", output = "http://teamsService.typescomplexes.demo.soap.objis.com/Teams/getTeamResponse")
    public Team getTeam(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
