
package com.objis.demo.tp13.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloSoapServerService", targetNamespace = "http://soap.tp13.demo.objis.com/", wsdlLocation = "http://localhost:8888/hello?wsdl")
public class HelloSoapServerService
    extends Service
{

    private final static URL HELLOSOAPSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOSOAPSERVERSERVICE_EXCEPTION;
    private final static QName HELLOSOAPSERVERSERVICE_QNAME = new QName("http://soap.tp13.demo.objis.com/", "HelloSoapServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOSOAPSERVERSERVICE_WSDL_LOCATION = url;
        HELLOSOAPSERVERSERVICE_EXCEPTION = e;
    }

    public HelloSoapServerService() {
        super(__getWsdlLocation(), HELLOSOAPSERVERSERVICE_QNAME);
    }

    public HelloSoapServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOSOAPSERVERSERVICE_QNAME, features);
    }

    public HelloSoapServerService(URL wsdlLocation) {
        super(wsdlLocation, HELLOSOAPSERVERSERVICE_QNAME);
    }

    public HelloSoapServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOSOAPSERVERSERVICE_QNAME, features);
    }

    public HelloSoapServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloSoapServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IHello
     */
    @WebEndpoint(name = "HelloSoapServerPort")
    public IHello getHelloSoapServerPort() {
        return super.getPort(new QName("http://soap.tp13.demo.objis.com/", "HelloSoapServerPort"), IHello.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHello
     */
    @WebEndpoint(name = "HelloSoapServerPort")
    public IHello getHelloSoapServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.tp13.demo.objis.com/", "HelloSoapServerPort"), IHello.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOSOAPSERVERSERVICE_EXCEPTION!= null) {
            throw HELLOSOAPSERVERSERVICE_EXCEPTION;
        }
        return HELLOSOAPSERVERSERVICE_WSDL_LOCATION;
    }

}
