
package com.objis.demo.tp13.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHello", targetNamespace = "http://soap.tp13.demo.objis.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IHello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "reponse", partName = "reponse")
    @Action(input = "http://soap.tp13.demo.objis.com/IHello/sayHelloRequest", output = "http://soap.tp13.demo.objis.com/IHello/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
